FROM openjdk:latest

ARG DATABASE_URL
ARG DATABASE_USER
ARG DATABASE_PASSWORD

ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_USERNAME=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD

COPY ../build/libs/chapterTwo-0.0.1-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]